language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
install:
    - './setup.py develop'
    - "pip install -e '.[tests]'"
script:
    - pylama
    - py.test -vvvv --showlocals
sudo: false
